### ISSUE TITLE
Add support for widgets

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#127]
As an user, I want to be able to track key factors from the Petals app in my home screen, as a widget.

- [ ] Time Sober (the timer/clock since last use)
- [ ] Health measurements (Current discomfort/estimated THC concentration)
- [ ] Break period (on or off?)
- [ ] Hit Timer (Stop/Start/Reset + Control Vibration)

-----

<details>
<summary>Some widget examples from other apps</summary>

![image](https://user-images.githubusercontent.com/1577251/198040192-f2002383-dd69-4621-a03a-f50402446ba4.png)
![image](https://user-images.githubusercontent.com/1577251/198040470-ab46cf77-6a8b-4216-a52a-f9a968e70ca4.png)
![image](https://user-images.githubusercontent.com/1577251/198040575-3d1a0083-fe10-4657-8c8f-181f5766b8ef.png)

</details>

**Comment by SolainOG** [comment]
A widget to stop/start/teset the hit timer would be great :)

**Comment by darkralts** [comment]
I would also love a widget for the clock since last usage,

**Comment by Zealous00** [comment]
Hello, I would like to work on this issue if possible, could you assign it to me please? :)

**Comment by LeoColman** [comment]
Absolutely!
Assigned to youu @Zealous00

**Comment by Zealous00** [comment]
@LeoColman Thanks! Will do my best!
