### ISSUE TITLE
3 Decimal Places for all cost related stats

### ISSUE THREAD

**Issue by MeisterBubatz** [LeoColman/Petals#128]
**Describe the bug**
Cost per gram is showing 3 decimal places instead of 2

**App version and source**
Where did you download Petals from? Which version are you in?
F-Droid version, so 3.1.3

**To Reproduce**
1. Go to 'Usage'
2. Shows 3 decimal places on each $ category

**Expected behavior**
Show 2 decimal places

**Screenshots**
![Screenshot_20221103_001012](https://user-images.githubusercontent.com/113553705/199620046-3dbca997-f980-4c8d-8adf-e831289694a3.jpg)

**Additional context**

**Comment by LeoColman** [comment]
There are plenty of use cases where the third decimal is needed.

- Some currencies can use 3 decimal places. [This documentation](https://docs.adyen.com/development-resources/currency-codes) from Adyen show some examples
- When converting from Oz to Grams or splitting the price one might also come with a broken down number.
- Let's say 5g is 100, 10g is 200 but 15g is 250. 250/15 would lead us to 16.667 per gram. Some users might round it to 16.5, some to 16, some to 17

Dropping the 3 decimal places is too harsh.

Do you propose to take it to .00 if it would be .000?

Or perhaps we can add this as an option in the settings, the amount of decimal places/precision we want displayed.
