### ISSUE TITLE
Timer reset

### ISSUE THREAD

**Issue by quad-one** [LeoColman/Petals#185]
The hit timer resets the moment the screen rotates.

3.3.1 F-Droid

**Comment by LeoColman** [comment]
Nice find!

**Comment by LeoColman** [comment]
https://github.com/LeoColman/Petals/blob/67be4899823ff61134d258bc5dd4a146c6553fee/app/src/main/kotlin/br/com/colman/petals/hittimer/ComposeHitTimer.kt#L72

Code related to it probably around here

**Comment by LeoColman** [comment]
https://developer.android.com/jetpack/compose/state

> While remember helps you retain state across recompositions, the state is not retained across configuration changes. For this, you must use rememberSaveable. rememberSaveable automatically saves any value that can be saved in a Bundle. For other values, you can pass in a custom saver object.
