### ISSUE TITLE
Add option to purchase ad free option

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#209]

**Comment by LeoColman** [comment]
Product ID `petals_remove_ads`

**Comment by rahim001-sudo** [comment]
Hello Leo.
I am interested in implementing this feature.
Can i work on this ?.

**Comment by LeoColman** [comment]
Hello Rahim!

Yes! Thanks for your interest! If you have any questions let me know

**Comment by rahim001-sudo** [comment]
Thanks Leo :) .
I will definitely let you know if i will have any.

**Comment by rahim001-sudo** [comment]
Hi Leo.
I have done the code for inAppPurchase but the products are not returned even for testId (android.test.purchased). do we need to enable license testing and register as a tester in play console?.

from coding part i thinks its good.

**Comment by LeoColman** [comment]
I see. Thanks Rahim!

Would you like to share an e-mail address to put as a license tester or would rather open the PR and leave this part to me?

**Comment by rahim001-sudo** [comment]
I have opened a PR.
Actually I am new to open source and github commands So. . Please let me know if thats good enough or i will make the PR Again if there are any changes needed.

**Comment by LeoColman** [comment]
No problem at all! 
Welcome to open source 😁

Next step is to ensure repository checks are passing and then I'll review the code.

You'll be able to see the comments on the pr itself when I make them, and add new commits to fix them.

Once we are done we'll squash all the commits in one and merge it to the main branch

**Comment by rahim001-sudo** [comment]
Yaa i had seen it was pending before.
The repository checks happens by themselves right after the PR is opened?.

i am googling it but is it possible to know if all the checks will pass or not locally in the system itself ?.
i will look into these build issues and will update again.

**Comment by LeoColman** [comment]
> i am googling it but is it possible to know if all the checks will pass or not locally in the system itself 

Yes, you need to check the commands that are executed in each workflow in the `.github` directory. The mains ones are the linter (Detekt) and build workflows

**Comment by rahim001-sudo** [comment]
Yes i had checked them out.  i found out you can use ACT(https://github.com/nektos/act) for that running actions locally.
