### ISSUE TITLE
F-Droid can't build - unknown maven repo

### ISSUE THREAD

**Issue by licaon-kter** [LeoColman/Petals#228]
ref: https://github.com/LeoColman/Petals/commit/64a8c863a3f34d964fe366bcb2d999df48a26939#diff-8cff73265af19c059547b76aca8882cbaa3209291406f52df1dafbbc78e80c46R37

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3676497648#L1616

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/7f8a19d1f1492e37cdee7a1bad538a5084f6abe6

**Comment by licaon-kter** [comment]
You don't use.

We can build from source?

**Comment by LeoColman** [comment]
> You don't use.

Ah, I see.
#205 was where this work was started. I added the pre-release version that comes from Google MVN repository.

As the official version was released, This won't be a big issue as I'll be able to remove that repository.
Perhaps it should be added as one of the supported repositories?

[Official Android Developer page with repo link](https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility)

[Actual project](https://androidx.dev/storage/compose-compiler/repository)

**Comment by licaon-kter** [comment]
> Perhaps it should be added as one of the supported repositories?

Even the ones we have tend to be problematic sometimes: https://f-droid.org/en/2022/07/22/maven-central.html

**Comment by LeoColman** [comment]
I've read that post when it came out, it was a very nice read!
Thanks for the help and support @licaon-kter :)

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/97499341b9aa928a70abb1326c981a26b98852d7
