### ISSUE TITLE
Add multiple pauses per day

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#244]

**Comment by markopex** [comment]
Can you please check the video? Is this how it should works? I guess design needs update, especially pause list, maybe would be good to be dialog or separate page?

https://github.com/LeoColman/Petals/assets/26334319/5c712283-3317-44e9-ba9b-6d1020bb4cee

**Comment by LeoColman** [comment]
That looks pretty!

I agree that perhaps this needs a design update. We can use your video as a first implementation and then move the components elsewhere when we have a new page designed.

I'm thinking in the future in merging Hit Timer + Symptoms + Pauses in a single "Damage Reduction" page, and I don't think we would need to change the components that you designed here
