### ISSUE TITLE
Add toast message when use is deleted

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#245]
"have I actually touched the button? I forgot"

**Comment by azmatroshan** [comment]
@LeoColman assign it to me I want to contribute to this and please tell me what should be the Toast message.

**Comment by LeoColman** [comment]
I think something like "Use X deleted", and if possible an undo button that lasts like 5s.

I didn't think this one too thoroughly. 

The problem to solve is "have I actually touched the button? I forgot"

**Comment by azmatroshan** [comment]
@LeoColman 
I have made a PR #247 regarding this issue

and,
Can you please explain me that why Lint/detekt failed?
