### ISSUE TITLE
Ability to turn off millisecond view.

### ISSUE THREAD

**Issue by Karei714** [LeoColman/Petals#249]
Feature request: Ability to select/deselect the view of the amount of time elapsed.
I would like to be able to not watch the millisecond counting up. (Because it gives me a headache and stops me from using this timer...)
Thanks.

**Comment by LeoColman** [comment]
Hi @Karei714 !

Thanks for the suggestion. This feature would be very nice to have!

![image](https://user-images.githubusercontent.com/1577251/219095624-b396c0ff-e308-4701-88d1-ffdd66011056.png)


Maybe adding it to a setting and leave it in the settings menu is enough for this kind of customization

**Comment by Anshu-Bijarnia** [comment]
Can i try to implement this feature ? I am new to open source contributions. 
Adding a simple show seconds in timer toggle button in the settings might be sufficient?

**Comment by LeoColman** [comment]
You have the right screen, yes.

To do the same on HitTimer I just created another issue, I think it's a good idea too https://github.com/LeoColman/Petals/issues/275

**Comment by Anshu-Bijarnia** [comment]
I will try to do both of these. Hopefully it wont be that hard.

**Comment by jhomatas48** [comment]
@Anshu-Bijarnia Any progress on these? If not I could contribute/help.

**Comment by evan-m7** [comment]
@Anshu-Bijarnia, I would love to help as well with @jhomatas48. Looking forward to hearing back!

**Comment by Anshu-Bijarnia** [comment]
@evan-m7 @jhomatas48 Go ahead, i was not able to look into it.

**Comment by LeoColman** [comment]
@evan-m7 Take this one! Thanks for the help!

@Anshu-Bijarnia Was it just a time issue? If you need help getting the project to run, please let us know!

**Comment by jhomatas48** [comment]
@LeoColman I'm trying to push a commit, but I'm running into authentication issues. I'm assuming it has to do with the git secrets; could you help me with this?

**Comment by LeoColman** [comment]
Permission denied when committing to Git?

If that's the case, did you remember to fork the project before trying to commit?

Apr 9, 2023 07:45:32 jhomatas48 ***@***.***>:

**Comment by jhomatas48** [comment]
@LeoColman Thanks, I just forgot to fork. I made a pull request
