### ISSUE TITLE
Add setting to specify precision on numbers

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#292]
We currently display 3 decimal places on all numbers displayed.

This should be configurable, as in most situations it's more than necessary.

![image](https://user-images.githubusercontent.com/1577251/230515316-c5e71b1b-dcb0-4d23-816a-831d32202f17.png)

**Comment by jhomatas48** [comment]
I'd like to work on this, going to try to add a setting allowing 0-3 decimals.

**Comment by LeoColman** [comment]
Seems good!
Thanks for the help!

**Comment by jhomatas48** [comment]
@LeoColman Which page(s) should this apply to? I have this currently applied to the home page but nothing else yet.

**Comment by LeoColman** [comment]
I think we can go with that first, then see if it's still a lacking setting in other points. What do you think?

**Comment by jhomatas48** [comment]
I think that's fine. I also made the default precision to 2 decimal places if that is ok? I applied this change to the stats page as well but it is not configurable.

**Comment by LeoColman** [comment]
Yes, I think it's ok for the default to be 2

**Comment by jhomatas48** [comment]
@LeoColman I have this working but for some reason am not able to scroll in the settings page when I added my setting. I can't figure out why this is

**Comment by LeoColman** [comment]
Could you try pulling commits from the main branch?
I've added this recently and maybe your branch is not up-to-date.

Otherwise, you can still push your pull request and I can help you QA and validate it :)

**Comment by jhomatas48** [comment]
@LeoColman Are you sure about this? I tried pulling and when I add anything new to the settings column, I'm unable to scroll.

**Comment by LeoColman** [comment]
Not so sure anymore.
Did a quick try on my phone and indeed it's not scrolling.

I'll check, created #313 to remember it

Apr 23, 2023 18:12:09 jhomatas48 ***@***.***>:

**Comment by jhomatas48** [comment]
Ok in the meantime, should I still create a pull request with the decimal precision setting?

**Comment by LeoColman** [comment]
Yes.
Both can travel separately.

If you already found the quickfix to make it scrollable, feel free to include it in the pull request

Apr 23, 2023 18:34:12 jhomatas48 ***@***.***>:

**Comment by jhomatas48** [comment]
Also wondering if there are any units tests I should add for the new features?
