### ISSUE TITLE
Add legislation and rights information

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#345]
As a damage reduction strategy I want to know what are my rights in case of a police approach and how much I'm allowed to carry (if at all) legally.

This information changes per country. We can start with 2 that @LeoColman has personal knowledge in:

- Brazil
- Canada

**Comment by D4NILO7** [comment]
Hi, I would like to work on this issue as an university project in the next few weeks... Can you assign this issue for me ? Maybe can you provide some more information how do you excpect this issue to be solved... I imagined some kind of solution on this topic, but I would like to discuss if it fits your expectations....Can we discuss these specifics later on ? Thanks for your help!

**Comment by LeoColman** [comment]
Absolutely!

My idea was to make a basic visualization on what is allowed and what are your rights for each country.

For example:

- In Canada/Quebec you can have on yourself 30g of cannabis and up to 4 female plants flowering.
- In Brazil it's illegal to carry weed, but there is a difference between a dealer and a user. 


General knowledge would be useful as well, such as "What should I do if approached by police".

We should make "Supported Countries" auto-detectable, but selectable. General Knowledge should be available for all countries.


----

This was my general idea, but I don't have much, so feel free to reshape this feature or even create a new one.

I'd start with legislation from wherever you are and expand from there
