### ISSUE TITLE
60 and 90 days line color in Stats page are too faint and confusable with the background color

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#372]

**Comment by pratistha-05** [comment]
can you please provide more description to this issue, so that i can start working on it?

**Comment by LeoColman** [comment]
Absolutely!

![Screenshot from 2023-12-06 21-22-07](https://github.com/LeoColman/Petals/assets/1577251/ac824618-5bd1-46a1-b10f-de9364c0cf0f)


This is the problem right here: When using the dark mode and selecting 90 days or 60 days, the background color is too close to the background color, and for this reason it's hard to read

**Comment by rishabh-jain-1990** [comment]
@LeoColman I have changed the colors of the 60 and 90 day line to Cyan and Orange, respectively. Changes are in this PR: https://github.com/LeoColman/Petals/pull/734
