### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [LeoColman/Petals#39]
```
AILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle
```

Could you please take a look? Thanks!

**Comment by LeoColman** [comment]
Absolutely!
Do you know which build it is from, or which version it's trying to build that is failing?

**Comment by LeoColman** [comment]
I think it's fixed in fdroid.
Please let me know if this issue pops up again.

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
I got the same error with 2.4.1.

**Comment by LeoColman** [comment]
I'll check it again
I thought it solved, but the build that passed was just the  metadata sync.

**Comment by LeoColman** [comment]
I think fdroid didn't try to build it yet for 241

**Comment by linsui** [comment]
I tried it [here](https://gitlab.com/linsui/fdroiddata/-/jobs/2670744456). You can also use the CI by forking the repo.

**Comment by LeoColman** [comment]
Ok, should be fixed now. It was a linter issue

**Comment by linsui** [comment]
I got the same error with 2.4.2. https://gitlab.com/linsui/fdroiddata/-/jobs/2671356466

**Comment by linsui** [comment]
Oh, I know what the problem is. The old prebuild script `sed -i -e '/val keystorePropertiesFile/,/^}/d' build.gradle.kts` doesn't work anymore and breaks the build. Sorry for bother you, I'll fix it.

**Comment by LeoColman** [comment]
Didn't bother me at all.
Loved the opportunity to learn a bit more about fdroid :)

Thanks
