### ISSUE TITLE
Improving the UI Design of the app.

### ISSUE THREAD

**Issue by bhaskarblur** [LeoColman/Petals#410]
**Is your feature request related to a problem? Please describe.**
Hi there, i feel this type of apps should have a strong influence over its users in order to make changes, and an intuitive & engaging UI can help this app to achieve it. I see there is a room of scope in improving the Design of the app.

Is this project open to accept UI design improvements so that i can contribute on them and code them as well

**Describe the solution you'd like**
I would like to improve the design of the app and code it as well, i am very good in UI Design and i've contributed to open source projects in design improvements before.

**Additional context**
Are the maintainers i mean this project is open to accept UI enhancements? please let me know, i can make some improvement mockups as well and share with you.

**Comment by LeoColman** [comment]
Ooooh! That would be a blessing!
A few months ago I asked for some help from someone that know a bit of visual ID, if you want to try to follow any of it to have a basis.

I'm absolutely open to UI enhancements! I'm a backend developer who pretends to do something in Android. Please shine your creativity anywhere you feel needed :D

[Apresentação Petals.pdf](https://github.com/LeoColman/Petals/files/12777343/Apresentacao.Petals.pdf)

**Comment by bhaskarblur** [comment]
Ok haha, i'll, unfortunately, i don't know much jetpack so it might take me time to bring improvements.
but i just wanted to confirm if you welcome UI changes.

Good to hear that, Thanks

**Comment by LeoColman** [comment]
If you want to post pictures with your suggestions, I might be able to implement them in compose

Oct 1, 2023 11:26:11 Bhaskar Kaura ***@***.***>:

**Comment by bhaskarblur** [comment]
ok, but i want to make pull request and become a direct contributor as well, 🙂
Can you help me in that way?

**Comment by LeoColman** [comment]
Absolutely!

Oct 1, 2023 11:40:28 Bhaskar Kaura ***@***.***>:

**Comment by bhaskarblur** [comment]
How can you help me with that? Like i redesign and you code and you give me some code that i push and some you push?
What can be a good way?

**Comment by LeoColman** [comment]
We can use the [Co-Authoring](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors)

I can also coach/point you to where changes should be made and you can try to figure it out to learn Compose

**Comment by bhaskarblur** [comment]
That sounds good, thank you.
So how should we connect further?

**Comment by bhaskarblur** [comment]
You can mail me at bhaskar7005blur@gmail.com , so that we can connect further, thank you.
Looking forward to connect & we'll improve each part of the app design gradually!

**Comment by bhaskarblur** [comment]
@LeoColman you there?

**Comment by patthhar** [comment]
I'd love to contribute to the ui changes using jetpack compose too! Let me know if I can help as well

**Comment by bhaskarblur** [comment]
Hi, @patthhar works, let connect via some way , i'll make the new designs whereas you can develop them,
And we can use Co-Authoring to contribute together.

**Comment by patthhar** [comment]
Sure let me email you

**Comment by bhaskarblur** [comment]
@patthhar When should we get started then?

**Comment by patthhar** [comment]
Whenever you have a design I'm happy to begin

**Comment by bhaskarblur** [comment]
ok then i'll soon
