### ISSUE TITLE
Feature request: change currency icon

### ISSUE THREAD

**Issue by KaffeMyers** [LeoColman/Petals#52]
As simple as that - a setting to change the currency symbol to one matching where you are, bonus feature would be if you also could replace the symbol for a three letter abbreviation, such as "USD", "EUR", "GBP" etc.

Not suggesting per entry setting, just general across the board.

**Comment by LeoColman** [comment]
https://github.com/LeoColman/Petals/blob/d9a06291721ccc0b5b8a666dd8e4f9365b1dad96/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt#L49

The approach today is pretty dumb:

1. If user language is PT-BR -> Symbol R$
2. Else -> Symbol $ 


We could detec Device Location and use the currency for the location
Or plain set it to a configurable value.

I think I like the second option more than the first

**Comment by KaffeMyers** [comment]
Definitely the second, if you ask me. Seems like that in combination with current approach (i.e. optional/manual override) is a smooth way to handle most situations fairly gracefully.

Thanks for the listen. :)

**Comment by LeoColman** [comment]
@KaffeMyers Implemented in 2.7.0
