### ISSUE TITLE
Make "hour of day" line in "stats" optional

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#536]
![Screenshot_20240408-150235_Petals](https://github.com/LeoColman/Petals/assets/1577251/645b4a2b-c9b9-4f2f-bb1a-f1a4c7fbf561)

This line should have a setting to control whether it's enabled or not

- new setting 
- i18n strings to describe it
- adapt both charts to the new setting

**Comment by rishabh-jain-1990** [comment]
@LeoColman Do we want it to be a toggle inside settings or a checkbox in the stats page itself?

**Comment by LeoColman** [comment]
Good question.

I think we want it in the stats page itself, but not as a checkbox to not confuse it with one of the day-range selectors.

----
I want to add more settings of this type in the future, such as "Sum / Average", so having a clear division between day checkboxes and switches denoting settings seems important.



Do you want to work on this issue?

**Comment by rishabh-jain-1990** [comment]
@LeoColman I can't see the line in the latest code. Has something changed?

**Comment by rishabh-jain-1990** [comment]
Implemented in https://github.com/LeoColman/Petals/pull/746

**Comment by rishabh-jain-1990** [comment]
@LeoColman Implemented in https://github.com/LeoColman/Petals/pull/746

**Comment by LeoColman** [comment]
Closed by @rishabh-jain-1990 as per #746 

Thanks!
