### ISSUE TITLE
No vibration in hit timer

### ISSUE THREAD

**Issue by ih8ms** [LeoColman/Petals#542]
**Describe the bug**
Although the box is checked, there is no vibration at the end of the hit timer.

**App version and source**
3.21.1 from F-Droid

**To Reproduce**
1. Go to 'Hit Timer'
2. Check the box 'Vibrate on timer end'
3. Start the timer
4. Wait for the timer to end
5. Timer ends, there is no vibration 

**Expected behavior**
The phone's vibration motor shall be activated for a certain amount of time or in a pattern etc.

**Screenshots**
no

**Additional context**
Media volume off, ringer volume low.

**Comment by LeoColman** [comment]
Thanks for the report @ih8ms !

I couldn't reproduce this on my Fairphone 3+ using the same version. I tried muting volume, enabling **Do Not Disturb** mode but still I got it to vibrate. 

Could you share your phone/emulator model for further investigation?

**Comment by ih8ms** [comment]
I found that on my Pixel 6 (Android 14) that you need to enable "touch feedback" to make vibration work. However, I had disabled that for reasons. Arguably, this isn't exactly touch feedback either 😉

Regardless, I think there is no "better" or "different" way to do this in the code, so no idea how this could be done another way. 🤔🤷🏼‍♂️

**Comment by LeoColman** [comment]
It seems to be a bug in Google/Pixel distributions

https://issuetracker.google.com/issues/311248120

I think it's a very similar problem to this one /\

Can you confirm it happens for you too?
