### ISSUE TITLE
Add one second in hit timer with ms off

### ISSUE THREAD

**Issue by ih8ms** [LeoColman/Petals#543]
**Is your feature request related to a problem? Please describe.**
When disabling milliseconds in the hit timer, the timer displays zero once time < 1s, e.g. 0,999. As this almost is a full second to 0.000, the 0 is dispayed for a second until it blinks (and vibrates, if enabled).

**Describe the solution you'd like**
The display should read 1 until it's really down to 0.000, even though the milliseconds aren't shown. It shall only start to blink and vibrate once it reaches/dispays zero. I guess that therefore 1 must be added to every second.

**Describe alternatives you've considered**
I don't see one.

**Additional context**
no

**Comment by LeoColman** [comment]
Nice catch!
Added a fix in PR #544 . 
Thanks!

**Comment by LeoColman** [comment]
I had to choose between 
- One second lasting for 2 seconds
- Adding an extra second just for display purposes --  Breaking the purpose of the screen


I decided to go with a middle ground:

![image](https://github.com/LeoColman/Petals/assets/1577251/202e6543-ff25-42a5-a1c3-ea7e6feea2c9)


Only when less than 1 second a single digit of the milliseconds will be displayed, making it clear that we are transitioning to 0.
