### ISSUE TITLE
Crashes on symptoms page after adding usage

### ISSUE THREAD

**Issue by 0x80085** [LeoColman/Petals#55]
Install app
Add usage (5 grams, 10 /g)
Seevthe stat page with the ticking dtats isn't displayed properly
Tap nav item to go to symptoms page
App crashes
Even after restarts, keeps crashin on that page

**Comment by LeoColman** [comment]
Hi!
Could you please tell me which version you're using?

**Comment by 0x80085** [comment]
Hmm after a reinstall every issue appears to have disappeared. Was and am using latest from f droid 2.6.0.

**Comment by LeoColman** [comment]
Good to know :)
