### ISSUE TITLE
Add small version number on the header near the app name 

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#557]
To ease debugging and maybe eventually place a "new version available" icon

**Comment by Anshu-Bijarnia** [comment]
![img](https://github.com/LeoColman/Petals/assets/86189784/05ee8e77-23d2-4a28-a0d5-a0f17da4409c)
Is it the correct area to place the version number? I would like to take up this issue

**Comment by LeoColman** [comment]
Yes. If it occupies too much space we can try to see if it fits under it.
Let me assign it to you!

**Comment by Anshu-Bijarnia** [comment]
![Screenshot_20240501-193624](https://github.com/LeoColman/Petals/assets/86189784/841bc3ef-5d7f-4163-b57b-605ecdfbbe45)
Will this work? suggest any changes if needed

**Comment by LeoColman** [comment]
I think we should bring it way closer to the app name itself, and not an independent block on the header as it looks like.

Sizing and strings looks perfect tho

**Comment by Anshu-Bijarnia** [comment]
![Screenshot_20240501-211349](https://github.com/LeoColman/Petals/assets/86189784/7445c25f-5821-4974-8bd8-f0a3fedba8d5)
Is this fine?

**Comment by LeoColman** [comment]
Align base-to-base and I think we're good to go!

**Comment by Anshu-Bijarnia** [comment]
Created a PR.

**Comment by LeoColman** [comment]
Thanks @Anshu-Bijarnia !!
