### ISSUE TITLE
Add setting for date format

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#67]
**Is your feature request related to a problem? Please describe.**
Today I'm forced to use the date/time format that the app specifies

**Describe the solution you'd like**
In the settings screen I'd like to customize date and time format

**Comment by mkicina** [comment]
Hi, as I mention in the previous issue: https://github.com/LeoColman/Petals/issues/66

I would like to contribute to this one. You can tell me more about what customization are you expecting.

**Comment by LeoColman** [comment]
Let's take the two screenshots below as an example:

<details>
<summary>Screenshots</summary>
![image](https://user-images.githubusercontent.com/1577251/207358792-e34e0e1a-cd10-4951-9356-09c65a7bb871.png)
![image](https://user-images.githubusercontent.com/1577251/207358817-64517c5c-05ce-49e2-beca-684d9ab3af19.png)



</details>

Do you see that the date format is generally yyyy/MM/dd?
And that the time format is usually 24h HH:mm format

I'd like these to be configurable, so that we can support more customizations from users

**Comment by mkicina** [comment]
I understand about what is it right now.

I am asking about customization itself. Do you want that user can select from different date / time formats which will be provided in some dropdown in settings view? Sounds good?

**Comment by LeoColman** [comment]
Sounds good.
Make sure to include the international ISO 8601 as an option
