### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by Wombosvideo** [LeoColman/Petals#68]
**Is your feature request related to a problem? Please describe.**
When using this app I am mostly outside in the dark and my eyes start to get red, also from the blindingly bright screen.

**Describe the solution you'd like**
I'd like to have an option to turn the app into dark mode which would be a little easier on the eyes.

**Describe alternatives you've considered**
I tried to turn down the brightness but I was still in discomfort of the brightness. Also I know there is an option "Override Force Dark" or similar, allowing to turn _any_ app into a non-eye-straining experience but it doesn't work in this app.
Another addition could be to adapt to the phones setting, because my phone is already set to dark. 

**Additional context**
Yes.

**Comment by LeoColman** [comment]
Thanks for the suggestion!
I agree, having a dark mode is a necessity.

**Comment by Krishpandya682** [comment]
I would like to work on this issue

**Comment by LeoColman** [comment]
Take it, @Krishpandya682 !
I think a good place for the setting is in the settings package
https://github.com/LeoColman/Petals/tree/main/app/src/main/kotlin/br/com/colman/petals/settings

The theme of the app will have to adapt in response to it, but I'm not really sure how yet. Feel free to make your ideas into a PR!

**Comment by LeoColman** [comment]
https://github.com/LeoColman/Petals/commit/26b2746fd80ea8df7a65710374e999c01939e0f3

This commit may give some insights as well

**Comment by Krishpandya682** [comment]
Hi Sorry, can you help me get started, I am unable to run the app using Android Studio

**Comment by LeoColman** [comment]
Absolutely!
What is Android studio telling you?

**Comment by LeoColman** [comment]
Hey @Krishpandya682 !
Were you able to have any advance in this issue?

**Comment by Krishpandya682** [comment]
Hi @LeoColman . Sorry I forgot to inform you but I will no longer be able to work on this issue as my computer is down. Sorry.

**Comment by LeoColman** [comment]
Don't worry!
I'm sorry about your pc.
![image](https://user-images.githubusercontent.com/1577251/185617384-272d15d4-4cab-49e3-acfc-2ae7093ea8ce.png)

**Comment by LeoColman** [comment]
@Wombosvideo 
I've added dark mode following system. Release 2.8.0
If needed we can also add a setting specifically to that, but I'll wait for someone to ask that before adding too many things in the settings page.
