### ISSUE TITLE
add support for other languages

### ISSUE THREAD

**Issue by ivanchoff** [LeoColman/Petals#88]
it would be great to use the app in other languages (spanish for example)

**Comment by LeoColman** [comment]
You're right!
I'll see how to integrate community translations for the languages I don't personally speak

**Comment by ivanchoff** [comment]
I would like to contribute... this is a great app, thanks you!!

**Comment by LeoColman** [comment]
Added support for this using Weblate.
Spanish is there if you want to provide the translations :)
